services:
  smmm-website:
    build:
      # O contexto agora é a raiz do projeto '.'
      context: .
      # Especificamos o caminho para o Dockerfile do Nginx
      dockerfile: ./nginx/Dockerfile
    container_name: smmm-website
    restart: unless-stopped
    depends_on:
      - admin-backend

  admin-backend:
    build:
      context: ./admin-backend
    container_name: admin-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - PORT=3000