services:
  smmm-website:
    build:
      context: ./nginx
    container_name: smmm-website
    restart: unless-stopped
    volumes:
      - ./static-site:/usr/share/nginx/html:ro
    depends_on:
      - admin-backend
    # --- ADICIONE O COMANDO ABAIXO ---
    command: >
      sh -c "
        chmod 755 /usr/share/nginx/html &&
        chmod 644 /usr/share/nginx/html/* &&
        nginx -g 'daemon off;'
      "

  admin-backend:
    build:
      context: ./admin-backend
    container_name: admin-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - PORT=3000