services:
  smmm-website:
    build:
      context: ./nginx
    container_name: smmm-website
    restart: unless-stopped
    # A SEÇÃO 'volumes' E 'command' FORAM COMPLETAMENTE REMOVIDAS!
    # O contêiner agora é 100% autônomo.
    depends_on:
      - admin-backend

  admin-backend:
    build:
      context: ./admin-backend
    container_name: admin-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - N8N_WEBHOOK_BASE_URL=${N8N_WEBHOOK_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - PORT=3000